### PR TITLE
Gradient

### PR DESCRIPTION
**Pull request by tobson**

### CODE REVIEW

**Comment by tobson** [comment]
I'm not sure why this is failing. It works on my laptop.

@tberlok Can you test this on your laptop/desktop?

**Comment by tberlok** [comment]
I will check it tomorrow or the day after when I get to San Francisco.
The internet is basically non-existent in Yosemite.

2016-11-04 23:14 GMT-07.00, Tobias Heinemann notifications@github.com:

**Comment by tberlok** [comment]
It has to do with the import of a submodule. The errors on Travis are all
`'No module named 'skeletor.operators''`
but I can't figure out how to solve it right now. It works fine on my laptop. Maybe the solution is setting the PYTHONPATH to include the root on Travis?

**Comment by tobson** [comment]
Yes, I forgot that the Travis script users `python setup.py install`. This can probably reproduced on our laptops if we do that as well and we don't set `PYTHONPATH`.

**Comment by tobson** [comment]
I've merged in your change and made one myself where I modified `setup.py`. Let's see if this works now...

**Comment by tobson** [comment]
@tberlok Hold off on pulling this `gradient` branch for the time being. If it works I'm gonna overwrite the last commit to fix the typo in the commit message.

**Comment by tobson** [comment]
1 out of 15 tests failed. I'm gonna overwrite anyway.

**Comment by tobson** [comment]
Travis was still installing spectralDNS' mpiFFT4py instead of your fork. I suspect it'll work now.

**Comment by tobson** [comment]
Alright, good.

So there are a few changes that I'd like to make on the gradient branch before merging it back into master (which barring any major changes on the latter should be trivial now). Shall we perhaps discuss this on Skype?

**Comment by tberlok** [comment]
I can Skype now?

**Pull request merged**
