### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by tobson**

### CODE REVIEW

**Comment by tobson** [comment]
@tberlok Please check if [this line](https://github.com/nbia-astro/skeletor/blob/6a954c2cc4af44552238171e751d2b6ad813f96c/skeletor/initial_condition.py#L94) is correct. I made this change just so that it looks more similar to the corresponding code in the InitialCondition class.

**Comment by tobson** [comment]
Also, not that I see an immediate use case for this, but we could also get a noisy start with a coherent density perturbation by letting `U` be a uniformly distributed random number, right?

**Comment by tberlok** [comment]
Regarding the noisy start: That should work, yes.

**Comment by tberlok** [comment]
Regarding the lines: I think this will not work anymore as ky*y1 will not be the same as before. So if y1 is in grid units ky should be iky*2*pi/ny.

I think I prefer the previous solution where we converted just before storing the result in the particle array.

**Comment by tobson** [comment]
In `DensityPerturbation.__call__()`, the new `y1` isn't actually in grid units. I just changed the expression so that it's `y1` as defined in `InitialCondition.__call__()` times `manifold.dy`.

**Comment by tobson** [comment]
I'll merge this in if this test succeeds. It has `Lx=4` so it should be sensitive to not getting the units of the particle positions right.

**Comment by tberlok** [comment]
You need to add sympy to requirements.txt

**Comment by tobson** [comment]
I love GitHub.

**Comment by tberlok** [comment]
We can rebase and merge now, right?

**Comment by tobson** [comment]
Yep.

**Pull request merged**
