### PR TITLE
Fastwave and cicrcular wave as tests

### PR DESCRIPTION
**Pull request by tberlok**
I thought it would be nice to actually have these experiments run as tests.

### CODE REVIEW

**Comment by tberlok** [comment]
This fails because travis can't find the dispersion_solvers module. Do you know how to solve this?

**Comment by tobson** [comment]
I suspect this will work now.

**Comment by tberlok** [comment]
Do you understand how the pull request is passing but the other one does not? And it seems to be the ion-acoustic test that is failing although that has not even been modified.

**Comment by tobson** [comment]
I was gonna ask you the save thing. I don't understand this.

**Comment by tberlok** [comment]
It's a complete mystery to me. I have even tried to rerun the build on travis a few times. I just pushed a trivial change to if this helps.

**Comment by tberlok** [comment]
OK, now it works. I will let you merge it in!

**Comment by tobson** [comment]
Weird, but alright. Let's merge this in.

**Pull request merged**
